"""basically models are updated.

Revision ID: 1ffaeac14335
Revises: 0fc79e856203
Create Date: 2026-01-14 09:16:26.010582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffaeac14335'
down_revision = '0fc79e856203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('post_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('post_count')
        batch_op.drop_column('thread_type')

    # ### end Alembic commands ###
